### PR TITLE
Fix responsiveness on mobile

### PR DESCRIPTION
**Pull request by BrainBuzzer**
The previous commit was not making the page responsive on mobile so here's a fix for that. And the visual performance on computer is increased.

Live Demo: https://brainbuzzer.github.io/asksusi.com/chat

Image:

### CODE REVIEW

**Comment by mariobehling** [comment]
@BrainBuzzer Thanks for your contribution.  Please help us to keep the review process easy for reviewers.

Follow best practices. Open issues for bugs and features, match PRs to issues, add screenshots and links to your deployed service to showcase changes. 

Thanks.

**Comment by BrainBuzzer** [comment]
https://brainbuzzer.github.io/asksusi.com/chat

**Comment by jig08** [comment]
@BrainBuzzer , I have opened an issue for it (Issue https://github.com/fossasia/asksusi.com/issues/41) 

* Add detailed problem along with screenshot in issue description
* Edit your commit message and change it to `Fixes issue #41: <commit message>`
* Include relevant screenshots and demo links in this PR description for easier review.

Cheers !

**Comment by BrainBuzzer** [comment]
@jig08 @mariobehling please check this PR. It is just for the improvement of the site and visual elements on Small screens.

**Pull request merged**
