### PR TITLE
related to issue #29 (it is closed)

### PR DESCRIPTION
**Pull request by adityak1121**
This is related to issue #29. I have created a new start page. This is kept minimal and straight to the point. It won't look that much good with the design.

- Added Angular JS routing and Angular Framework.
- For the front-end, used Semantic-UI because that is only good option available for all files.
- Implemented a gray top bar.
- Font-awesome is also added.
- Added Google Font Roboto.
- Responsive Web app

### CODE REVIEW

**Comment by jig08** [comment]
* Did you take up the issue or start a discussion with the mentors before taking it up ?
* Where is the demo link and relevant screenshots ?
* Too many commits, Not a good practice.

**Comment by adityak1121** [comment]
I saw the issue #29, read it, and made a new start page for https://asksusi.com
Here are my self made start page screenshots, with responsiveness:
screenshot_mobile
screenshot_desktop

**Comment by adityak1121** [comment]
see this page on https://adityak1121.github.io/asksusi.com/#!/

**Comment by adityak1121** [comment]
sorry for the number of commits

**Comment by adityak1121** [comment]
how can i resolve this issue?

**Comment by jig08** [comment]
@adityak1121 

* This is not a valid PR. Once the issue is closed, it means that the issue has been resolved already.
* As the new page has already been implemented, you can now add your features or enhance the UI/UX of it. Try opening new issues for it.
* As far as the number of commits is concerned, you need to squash them up. Read [this article](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) maybe.
* To contribute further, either take up previous unassigned issues or open issues for feautures you think are missing.

Thanks ! Closing this PR.

**Comment by adityak1121** [comment]
Sorry, I thought that I could still make a pull request even after it is closed, I only saw a little thing, which was the gray top bar and changed the picture and some text which seems to be more inviting the people for downloading the SUSI app and view the SUSI server on Github, also I saw that even the issue #29 was closed, the PR #44 of @Ch-Developer was merged, so I thought my PR could also be merged by someone.
I thought that this issue is specifically related to GCi, so the mentors won't mind.

**Comment by jig08** [comment]
Anyway, you are still welcome to suggest changes and help resolve bugs. Cheers :)

**Pull request closed without merging**
