### PR TITLE
GCI: New Start Page

### PR DESCRIPTION
**Pull request by BrainBuzzer**
This is related to issue #29. I have created a new start page. This is kept minimal and straight to the point. It won't look good with the design of chat, so I had to link that to the different page. 

-The new link to previous start page is at /chat.
- I have added AngularJS routing and Angular Framework. 
- For the front-end, I have used Semantic-UI because that is only good option available for all files. 
- Font-awesome is also added.

### CODE REVIEW

**Comment by jig08** [comment]
@BrainBuzzer 

* Squash all your commits into one and rename it to something meaningful, such as "Deigning new asksusi.com page"
* Also provide the link to live `gh-pages` from your forked repository or relevant screenshot for easier review.

Cheers !

**Comment by BrainBuzzer** [comment]
I have done it. 
Screenshots - Check URLs and responsiveness.
http://imgur.com/a/auBch

**Comment by jig08** [comment]
@BrainBuzzer Avoid using external web-apps for posting screenshots, upload them here in the comments section only.

**Comment by BrainBuzzer** [comment]
I didn't know that was a rule. I am sorry.

**Comment by jig08** [comment]
@BrainBuzzer not exactly a rule, but it prevents dependencies.

Looks bland in my opinion, I suggest taking inspiration from [allo.google.com](https://allo.google.com/)

**Comment by BrainBuzzer** [comment]
Allo has a lots of features. SUSI is still in early stage of development. And I have seen a lot of bugs. It is not a complete AI yet. It just replies to specific question and sometimes even gets them wrong. In my opinion, as for now, this page should do it until susi is not getting out of pre-alpha stage (that's what I think)

**Comment by jig08** [comment]
@BrainBuzzer 
Yes ofc, SUSI is still a baby. I meant to take inspiration and not exact copy.
You can use a similar format maybe and include a few screenshots, GIFs etc to make it look a bit more inviting :)

**Comment by BrainBuzzer** [comment]
Minimal is best. That's the best I could come up with for SUSI. Even I had faced a lots of issues just to get that one screenshot. As there will be more features and better designs, I would add them. But adding any more of screenshots at this time point is completely absurd.

**Comment by mariobehling** [comment]
@BrainBuzzer @hpdang Thanks! Excellent start. Approving this. Let's go from there and do step by step improvements. Cheers!

**Comment by hpdang** [comment]
Good job!

**Comment by daminisatya** [comment]
Looks great!

**Comment by BrainBuzzer** [comment]
Thanks. I am still adding a carousel for desktop and just a regular page. It is almost finished because I thought I should make improvement to be sure my task is complete. I will add another pull request.

**Pull request merged**
